change streaming server url
Stremio/stremio-web pull request #178
Opened 2020-05-29 10:30 UTC by tymmesyde

#168

2020-06-03 14:46 UTC, nklhtv requested changes
Thank you for the PR!
Although its working and the code is great i don't think it provides good UX. It's not clear at all that user must hit enter key after changeing the url.
What i am proposing is to change the url input to a button that opens modal dialog with input field and submit button. 
Check "Add addon" button in addons route. It has the exact same behavior i've described.

2020-06-04 06:20 UTC, tymmesyde commented
Yeah, it wasn't ideal..
I think I managed to add your proposal, but I'm not sure about my implementation.
Maybe a dedicated modal dialog like `AddonDetailsModal` would be nice ? Since `addAddonModal` and `editServerUrlModal` _(the one I added)_ are similar.

2020-07-13 06:58 UTC, pedroslopez commented
Hi! What's the progress on this? I'd really love this feature

2020-07-14 13:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Stremio/stremio-web?pullRequest=178) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Stremio/stremio-web?pullRequest=178) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Stremio/stremio-web?pullRequest=178) it.</sub>

2020-07-14 14:47 UTC, nklhtv requested changes
I liked the changes in useProfileSettingsInputs.Could you bring them back? You could name the generic input like `serverUrlInput` with `value` and `onChange(value)` props, so in `editServerUrlOnSubmit` you will call `serverUrlInput.onChange(editServerUrlInputRef.current.value)` and use `serverUrlInput.value` in the JSX code

2020-07-14 14:47 UTC, nklhtv commented on src/routes/Settings/Settings.js
> +            if (typeof closeEditServerUrlModal === 'function') {
no need to check if that is a function here

2020-07-14 14:47 UTC, nklhtv commented on src/routes/Settings/Settings.js
> +                label: 'Edit',
That sould be named `Submit`

2020-07-14 14:47 UTC, nklhrstv commented on src/routes/Settings/styles.less
> +                                overflow: hidden;
everything is `overflow: hidden` by default

2020-07-14 14:47 UTC, nklhrstv commented on src/routes/Settings/Settings.js
> +                                <div className={styles['label']}>{profile.settings.streaming_server_url}</div>
add title attribute

2020-07-14 14:47 UTC, nklhrstv commented on src/routes/Settings/styles.less
> +    addon-modal-content: modal-dialog-content;
that should be named streaming-server-modal-content

2020-07-14 14:47 UTC, nklhrstv commented on src/routes/Settings/Settings.js
> +                                <Button className={classnames(styles['option-input-container'], styles['button-container'])} title={'Edit'} onClick={openEditServerUrlModal}>
this is not a good place for reuse settings grid class names
use `configure-button-container` class name and put all of its styles there: flex, display, align-items, justify-content, background-color, width&height: 3.5rem etc

2020-07-14 14:47 UTC, nklhrstv commented on src/routes/Settings/styles.less
> +                                flex: auto;
use `flex: none;` so it could remain square

2020-08-17 17:09 UTC, swetlasg approved these changes

2020-08-18 07:41 UTC, nklhtv approved these changes

2020-08-18 07:41 UTC, merged

2020-08-26 15:16 UTC, nklhrstv commented
Fixes #168