Adapt layout to mobile
Stremio/stremio-web pull request #269
Opened 2022-02-17 16:28 UTC by tymmesyde

2022-02-18 09:40 UTC, TRtomasz commented
Seems to be working fine on smaller screens!

2022-02-18 09:40 UTC, TRtomasz approved these changes, later dismissed

2022-05-09 12:53 UTC, nklhtv commented
This have to respect the mobile browsers setting for requesting desktop site

2022-05-09 12:53 UTC, nklhtv requested changes
This have to respect the mobile browsers setting for requesting desktop site

2022-06-13 15:58 UTC, nklhtv approved these changes

2022-06-13 15:59 UTC, nklhtv approved these changes

2022-06-13 15:59 UTC, merged