Add meta tags for iOS PWA support
Stremio/stremio-web pull request #291
Opened 2022-07-17 18:59 UTC by nperez0111

Add a couple of meta tags that allow "Add to Homescreen" on iOS to: A) Use the correct icon B) not just open the website in Safari, but open as a fullscreen app

2022-07-17 18:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Stremio/stremio-web?pullRequest=291) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Stremio/stremio-web?pullRequest=291) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Stremio/stremio-web?pullRequest=291) it.</sub>

2022-07-27 08:18 UTC, nklhtv commented
That looks nice!
can you add `apple-mobile-web-app-title` `Stremio` too ?
does `apple-touch-icon` needs to be after `title`? can you move it after `icon`?

2022-07-27 08:52 UTC, nklhtv requested changes
That looks nice!
can you add apple-mobile-web-app-title Stremio too ?
does apple-touch-icon needs to be after title? can you move it after icon?

2022-07-30 12:18 UTC, nperez0111 commented
Done & Done

2022-08-05 10:52 UTC, nklhtv commented
@nperez0111 Thank you for the contribution!

2022-08-05 10:52 UTC, nklhtv approved these changes

2022-08-05 10:52 UTC, merged