fix(Video): context menu was not working on Firefox
Stremio/stremio-web pull request #428
Opened 2023-07-18 21:14 UTC by tymmesyde

The context menu was not working on Firefox because the `contextmenu` event is not a PointerEvent on Firefox and we were using the pointerEvent property to check if it was from a mouse
https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event

The `contextmenu` event is managed by the browser, on desktop it should trigger on right click, on mobile on long press
So we don't really need to use the  `onLongPress` callback

2023-07-19 06:58 UTC, unclekingpin commented
There must be a better way to solve this because that will break UX on mobile safari.
Can we check if the nativeEvent is instance of PointerEvent and if its not then threat it as a mouse event
cc: @dexter21767-dev

2023-07-19 07:00 UTC, unclekingpin commented
```js
     const popupLabelOnContextMenu = React.useCallback((event) => {
        if (!event.nativeEvent.togglePopupPrevented && !event.nativeEvent.ctrlKey) {
            event.preventDefault();
            if (typeof event.nativeEvent.pointerType !== 'string' || event.nativeEvent.pointerType === 'mouse') {
                toggleMenu();
            }
        }
    }, [toggleMenu]);
    const popupLabelOnLongPress = React.useCallback((event) => {
        if (!event.nativeEvent.togglePopupPrevented && typeof event.nativeEvent.pointerType === 'string' && event.nativeEvent.pointerType !== 'mouse') {
            toggleMenu();
        }
    }, [toggleMenu]);
```

2023-07-20 12:54 UTC, TRtomasz requested changes
this indeed fix context menu but i noticed this in the console
![image](https://github.com/Stremio/stremio-web/assets/40594253/a7c4fc5f-0612-4e42-b246-479fcb3cc9cd)
Also for some reason i have no streams for movies using this build, not sure if it got broken with some other change

2023-07-20 13:06 UTC, tymmesyde commented
> this indeed fix context menu but i noticed this in the console ![image](https://user-images.githubusercontent.com/40594253/254888639-a7c4fc5f-0612-4e42-b246-479fcb3cc9cd.png) Also for some reason i have no streams for movies using this build, not sure if it got broken with some other change

The error was introduced in this PR: https://github.com/Stremio/stremio-web/pull/375
It's a prop check error so nothing too alarming

2023-07-20 19:52 UTC, unclekingpin submitted a review, later dismissed

2023-07-21 09:10 UTC, TRtomasz approved these changes

2023-07-21 09:16 UTC, merged