Version label was almost not visible
Stremio/stremio-web pull request #491
Opened 2023-10-20 12:12 UTC by tymmesyde

2023-10-24 01:01 UTC, gaurovgiri requested changes
Setting opacity to 0.3 will help distinguish the version info from the clickable buttons in settings which are of opacity 0.4.

2023-10-24 01:01 UTC, gaurovgiri commented on src/routes/Settings/styles.less
> +                opacity: 0.5;
```suggestion
                opacity: 0.3;
```

2023-10-25 11:49 UTC, kKaskak requested changes
It looks good with opacity 0.3, but it might require display changes on mobile. As it's brighter than before and fixed with the Navbar. What if we just put it in the same place as before but not fixed, visible only when you scroll down the settings and add some margin after it, so there is enough spacing between the label and the Navbar.

2023-10-25 11:53 UTC, gaurovgiri commented
@kKaskak Yeah, I think doing so might be better.

2023-10-25 12:45 UTC, kKaskak requested changes

2023-10-25 12:45 UTC, kKaskak commented on src/routes/Settings/styles.less
> +
@tymmesyde You can remove this as it works fine without specifying flex in the @minimum size too 👍

2023-10-25 12:45 UTC, kKaskak commented on src/routes/Settings/styles.less
>              .side-menu-container {
remove this too as its already specified with display: none on a higher resolution size

2023-10-25 12:47 UTC, kKaskak commented on src/routes/Settings/styles.less
> +
468-471

2023-10-25 12:47 UTC, kKaskak commented on src/routes/Settings/styles.less
>              .side-menu-container {
451-453

2023-10-25 12:49 UTC, tymmesyde commented on src/routes/Settings/styles.less
>              .side-menu-container {
It's better to make it clear what do we want to change for each screen sizes

2023-10-25 12:55 UTC, kKaskak approved these changes

2023-10-25 12:56 UTC, merged