translating type in board catalog titles
Stremio/stremio-web pull request #493
Opened 2023-10-22 18:40 UTC by VictorLutes

Uses translation for the catalog type (ie: Series, Movie, Channel, ...) in Board titles

PR will resolve https://github.com/Stremio/stremio-web/issues/453

2023-10-22 18:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Stremio/stremio-web?pullRequest=493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Stremio/stremio-web?pullRequest=493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Stremio/stremio-web?pullRequest=493) it.</sub>

2023-10-24 00:52 UTC, gaurovgiri approved these changes
LGTM

2023-12-08 16:23 UTC, unclekingpin requested changes
the issue is in stremio-core-web and the fix should start [from there](https://github.com/Stremio/stremio-core-web/blob/development/src/model/serialize_catalogs_with_extra.rs#L67C21-L75C23)
the `.title` should be replaced by `.type` and `.name` and the catalog title should be build in js

2024-01-03 15:08 UTC, tymmesyde commented
Closed in favor of https://github.com/Stremio/stremio-web/pull/540
Thank you for your contribution

2024-01-03 15:08 UTC, closed without merging