Add IINA & mpv as external players
Stremio/stremio-web pull request #513
Opened 2023-11-22 00:33 UTC by edde746

Depends on https://github.com/Stremio/stremio-core/pull/564

2023-11-22 01:39 UTC, edde746 commented
To explain the second commit, it cleans up the code and makes use of the users selected external player even if they are on desktop and have a working streaming server (previously it would disregard the selected external player unless the user was either on mobile or did not have a streaming server).

2023-11-22 07:08 UTC, tymmesyde commented
To support another external player, you need to add the uri schemes to the core
https://github.com/Stremio/stremio-core/blob/development/src/deep_links/mod.rs#L77

2023-11-22 09:10 UTC, elpiel requested changes
Thank you very much for your contribution!
This is a great addition to stremio-web.

2023-11-22 09:10 UTC, elpiel commented on src/common/externalPlayerOptions.js
> +    ]);
Until now VLC would have been an option for Macos but since your change only IINA & mpv are, so we need to add VLC back to the list.

- [ ] Please add the VLC player here as well.

2023-11-22 12:24 UTC, edde746 commented on src/common/externalPlayerOptions.js
> +    ]);
I'm pretty sure VLC does not work, but sure.

2023-11-25 14:26 UTC, kKaskak requested changes
While we are already on this, can we also add translation to the default option?

2023-11-25 16:04 UTC, edde746 commented
@kKaskak Are you sure you are commenting on the right PR? I have no idea what you mean since nothing in this PR is language specific...

2023-11-25 16:25 UTC, kKaskak commented
> @kKaskak Are you sure you are commenting on the right PR? I have no idea what you mean since nothing in this PR is language specific/can be translated...

https://github.com/Stremio/stremio-web/blob/39bdfba41d94ca498431e5fa99080a5dee46304a/src/common/externalPlayerOptions.js#L5

2023-11-25 16:32 UTC, edde746 commented
> This should most likely be translated.

[It already is?](https://github.com/Stremio/stremio-web/blob/development/src/routes/Settings/useProfileSettingsInputs.js#L200)

2023-11-25 16:40 UTC, kKaskak commented
> > This should most likely be translated.
> 
> [It already is?](https://github.com/Stremio/stremio-web/blob/development/src/routes/Settings/useProfileSettingsInputs.js#L200)

I tested it and it didn't translate that's why. 🤔 Will test again. If it works correctly -> approving.

2023-11-28 10:38 UTC, kKaskak commented
> > This should most likely be translated.
> 
> [It already is?](https://github.com/Stremio/stremio-web/blob/development/src/routes/Settings/useProfileSettingsInputs.js#L200)

In fact the translation was not implemented correctly, as you can see in the screenshots below. Pushed a fix to the branch.
<img width="831" alt="Screenshot 2023-11-27 at 11 40 00" src="https://github.com/Stremio/stremio-web/assets/117831817/0c87a934-12ed-4cd5-b937-9172113e63ab">
<img width="662" alt="Screenshot 2023-11-27 at 11 39 43" src="https://github.com/Stremio/stremio-web/assets/117831817/7a79ed7e-3625-4b6a-a633-ff7bcf0536bb">

2023-11-28 10:38 UTC, kKaskak submitted a review, later dismissed

2023-11-29 12:42 UTC, elpiel approved these changes, later dismissed

2023-12-18 14:20 UTC, tymmesyde approved these changes

2023-12-18 14:20 UTC, merged