Move manifest
Stremio/stremio-web pull request #522
Opened 2023-11-30 12:28 UTC by edde746

[The path to the manifest should be static](https://web.dev/articles/manifest-updates)

Also fixes #381.

2023-12-08 15:23 UTC, unclekingpin requested changes

2023-12-08 15:23 UTC, unclekingpin commented on webpack.config.js
> +            background_color: '#161523',
can we use stremio-colors here?

2023-12-08 15:23 UTC, unclekingpin commented on webpack.config.js
> +            screenshots : [
do we need screenshots?

2023-12-08 15:23 UTC, unclekingpin commented on webpack.config.js
> +                    sizes: [196, 512],
we used to have 192 and 512, are those the correct sizes?

2023-12-08 15:28 UTC, tymmesyde commented on webpack.config.js
> +            background_color: '#161523',
We can't since stremio-colors is not up to date with the latest redesign changes
But we could think about updating stremio-colors

2023-12-08 15:29 UTC, tymmesyde commented on webpack.config.js
> +            screenshots : [
It's useful for some stores or ways of prompting the user to install the app
It shows a warning in chrome Application/Manifest tab if not set

2023-12-08 15:30 UTC, tymmesyde commented on webpack.config.js
> +                    sizes: [196, 512],
The icon file is 512x512, this webpack plugin is handling the resizing of icons to those specified sizes

2023-12-08 15:55 UTC, unclekingpin approved these changes

2023-12-10 17:49 UTC, kKaskak approved these changes

2023-12-10 20:13 UTC, merged