Show fullscreen button on Safari desktop PWA
Stremio/stremio-web pull request #530
Opened 2023-12-06 21:46 UTC by edde746

With [Safari adding PWA support on desktop](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#Web-apps), `window.navigator.standalone` is no longer only true on iOS.

2023-12-06 22:53 UTC, kKaskak commented
<img width="1422" alt="Screenshot 2023-12-07 at 0 52 14" src="https://github.com/Stremio/stremio-web/assets/117831817/7fa01fc0-2b6b-4581-84ec-8bbb66947313">
I personally don't think this change is needed at all, as we already have a full screen button in the native app action buttons while running PWA on macOS. Leaving the review to @tymmesyde

2023-12-06 23:04 UTC, edde746 commented
The fullscreen button is completely unnecessary in Stremio web, but this makes the Safari PWA experience consistent with other browsers.

2023-12-08 15:55 UTC, unclekingpin requested changes
Can you check for [isMobile](https://github.com/Stremio/stremio-web/blob/development/src/common/platform.js#L25) to hide the fullscreen button

2023-12-08 20:10 UTC, edde746 commented
On Chrome on Android, you can enter fullscreen mode and on iOS it would be hidden since `document.fullscreenEnabled` is not true. It actually seems that Chrome on Android is one of the only places where the button is useful since there is no F11 key or other way to enter fullscreen mode.

2025-01-17 09:36 UTC, kKaskak commented
closed due inactivity

2025-01-17 09:36 UTC, closed without merging