Library infinite scroll
Stremio/stremio-web pull request #595
Opened 2024-02-27 10:00 UTC by tymmesyde

Related:
https://github.com/Stremio/stremio-core/pull/643
https://github.com/Stremio/stremio-core-web/pull/99

2024-02-29 07:49 UTC, elpiel submitted a review, later dismissed
Tested changes and the infinite scroll seems to be working.
Needs more testing to validate how well it's working as I had one or two instances where I've scrolled to the bottom very quickly with my touchpad and it didn't trigger the next set of LibraryItems

2024-03-08 21:49 UTC, kKaskak requested changes

2024-03-08 21:49 UTC, kKaskak commented on src/routes/Library/Library.js
> +        if (library.selected && library.selected.request.page === 1) {
```suggestion
        if (library.selected && library.selected.request.page === 1 && profile.auth !== null) {
```

2024-03-08 21:49 UTC, kKaskak commented on src/routes/Library/Library.js
> +        if (library.selected && library.selected.request.page === 1) {
It's crashing when the user is not logged in

2024-03-13 17:17 UTC, kKaskak approved these changes

2024-03-13 17:19 UTC, merged