feat(player): add seek action and handle seeking player state w/ debug statements
Stremio/stremio-web pull request #645
Opened 2024-05-16 16:39 UTC by elpiel

2024-11-18 13:51 UTC, kKaskak approved these changes, later dismissed

2024-11-18 13:55 UTC, kKaskak approved these changes, later dismissed

2024-11-20 14:49 UTC, tymmesyde commented on src/routes/Player/Player.js
> +        !seeking && setSeeking(true);
this check can be removed `!seeking &&`

2024-11-20 14:49 UTC, tymmesyde commented on src/routes/Player/Player.js
> +                seeking && setSeeking(false);
this check can be removed `!seeking &&`

2024-11-20 14:52 UTC, tymmesyde commented on src/routes/Player/Player.js
> +                            setSeeking(false);
`setSeeking(false);` is already present in `onPlayRequested()`

2024-11-20 14:56 UTC, tymmesyde commented on src/routes/Player/Player.js
>      }, [video.state.time, video.state.duration, video.state.manifest]);
`seeking` should be included in the useEffect deps

2024-11-20 15:13 UTC, tymmesyde commented on src/routes/Player/Player.js
> +        !seeking && setSeeking(true);
this check is unnecessary `!seeking &&`

2024-11-20 15:16 UTC, tymmesyde requested changes
If i play the video and start seek using the seekbar, the seek action will still be sent

2024-11-28 08:50 UTC, kKaskak approved these changes

2024-11-28 08:56 UTC, merged