feat: calendar
Stremio/stremio-web pull request #651
Opened 2024-06-18 10:10 UTC by tymmesyde

2024-07-04 18:38 UTC, kKaskak approved these changes, later dismissed

2024-10-30 12:26 UTC, elpiel requested changes
Works as expected.
Here are a few issues I found:
1. Posters don't show up on 1080p on my laptop, Desktop shows the posters, I expect it to work the same
2. I do not like using the UI elements "<" and ">" to go to the previous/next calendar, as they are too small, I prefer to keep the Desktop way of showing them (by name)
3. "Calendar" menu text gets trimmed

![Screenshot from 2024-10-30 13-01-49](https://github.com/user-attachments/assets/476c0580-812b-4e2d-b5d6-7340912265eb)

2024-11-19 22:43 UTC, kKaskak submitted a review, later dismissed
LGTM!

One thing to mention:

- The Calendar label is cut both on the desktop `VerticalNavbar` and while on mobile. (It will surely depend on the translations as well). Might not be entirely fixable.

2024-11-19 23:01 UTC, kKaskak approved these changes, later dismissed

2024-11-20 14:39 UTC, kKaskak submitted a review, later dismissed

2024-11-26 13:40 UTC, elpiel submitted a review, later dismissed

2024-11-28 13:35 UTC, elpiel submitted a review, later dismissed

2024-11-28 13:51 UTC, elpiel submitted a review, later dismissed

2024-11-28 15:25 UTC, merged