feat: Add label to subtitle tracks
Stremio/stremio-web pull request #688
Opened 2024-09-22 04:25 UTC by ArtificialSloth

Small change to include the subtitle's label below it's origin in the subtitle variant list.

Before:
![Screen Shot 2024-09-22 at 00 20 25](https://github.com/user-attachments/assets/dd7923fc-d6a8-45d6-8f4a-e586d30d9250)

After:
![Screen Shot 2024-09-22 at 00 03 04](https://github.com/user-attachments/assets/b0e301a6-795d-4ac3-b1db-749665912be4)

2024-09-22 05:14 UTC, ArtificialSloth commented
Added a check to prevent this:
![Screen Shot 2024-09-22 at 00 40 36](https://github.com/user-attachments/assets/40eba06b-4cb9-44bd-b6c1-35e549978090)

2024-11-18 13:22 UTC, kKaskak approved these changes

2024-11-20 08:38 UTC, kKaskak commented
Thank you for your contribution! LGTM

2024-11-20 09:46 UTC, kKaskak requested changes
Actually now looking atogehter with @tymmesyde we suggest some changes:

 - Swap places of `track.origin` and `track.label` since the second one is actually more important
 - If `track.label.startsWith('http')` Add a fallback to `track.lang` for the `label`
 - Translate the `track.origin` if possible (we have translations strings for some cases)
 https://github.com/Stremio/stremio-translations/blob/master/en-US.json#L1521

2024-11-20 10:38 UTC, kKaskak requested changes

2024-11-20 10:38 UTC, kKaskak commented on src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
> +                                        }
```suggestion
                                        {
                                            typeof track.label === 'string' && !track.label.startsWith('http') ?
                                                track.label
                                                :
                                                track.lang
                                        }
```

2024-11-20 10:38 UTC, kKaskak commented on src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
> +                                        }
to keep the overall conditionals structure

2024-11-20 10:44 UTC, kKaskak requested changes

2024-11-20 10:44 UTC, kKaskak commented on src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
> +                                        <div className={styles['variant-origin']}>{t(track.origin)}</div>
In some cases the origin is not fully visible as well. Could you please solve this issue as well?
![image](https://github.com/user-attachments/assets/3d91643a-137a-44dc-8307-47415791293f)

2024-11-20 13:02 UTC, kKaskak approved these changes
LGTM

2024-11-20 14:35 UTC, merged